contests/urls.py
from django.conf.urls import url

from . import views

app_name = 'contests'
urlpatterns = [
    url(r'^contests/$', views.list, name='list'),
    url(r'^contests/setup/$', views.ContestCreate.as_view(), name='setup_new'),
    url(r'^contest/(?P<contests_code>[-\w]+)/$', views.Description.as_view(),
        name='description'),
    url(r'^contest/(?P<contests_code>[-\w]+)/rules$', views.Rules.as_view(),
        name='rules'),
    url(r'^contest/(?P<contests_code>[-\w]+)/submit/$',
        views.Submit.as_view(), name='submit'),
    url(r'^contest/(?P<contests_code>[-\w]+)/submissions/$',
        views.Submissions.as_view(), name='submissions'),
    url(r'^contest/(?P<contests_code>[-\w]+)/my_submissions/$',
        views.MySubmissions.as_view(), name='my_submissions'),
    url(r'^contest/(?P<contests_code>[-\w]+)/'
        r'submission/(?P<submission_id>[0-9]+)/$',
        views.SubmissionView.as_view(), name='submission'),
    url(r'^contest/(?P<contests_code>[-\w]+)/'
        r'submission/(?P<submission_id>[0-9]+)/answer/$',
        views.DownloadSubmissionAnswer.as_view(), name='submission_answer'),
    url(r'^contest/(?P<contests_code>[-\w]+)/'
        r'submission/(?P<submission_id>[0-9]+)/source/$',
        views.DownloadSubmissionSource.as_view(), name='submission_source'),
    url(r'^contest/(?P<contests_code>[-\w]+)/'
        r'rejudge/(?P<submission_id>[0-9]+)/$',
        views.SubmissionRejudgeView.as_view(), name='rejudge'),
    url(r'^contest/(?P<contests_code>[-\w]+)/rejudge/$',
        views.ContestRejudgeView.as_view(), name='rejudge'),
    url(r'^contest/(?P<contests_code>[-\w]+)/setup/$',
        views.ContestUpdate.as_view(), name='setup'),
    url(r'^contest/(?P<contests_code>[-\w]+)/teams/$',
        views.Teams.as_view(), name='teams'),
    url(r'^contest/(?P<contests_code>[-\w]+)/teams/new$',
        views.TeamCreate.as_view(), name='new_team'),
    url(r'^contest/(?P<contests_code>[-\w]+)/team/(?P<team_id>[0-9]+)/$',
        views.TeamView.as_view(), name='team'),
    url(r'^contest/(?P<contests_code>[-\w]+)/team/(?P<team_id>[0-9]+)/join/$',
        views.JoinTeam.as_view(), name='join_team'),
    url(r'^contest/(?P<contests_code>[-\w]+)/'
        r'team/(?P<team_id>[0-9]+)/invite/$',
        views.TeamInvitationView.as_view(), name='invite_to_team'),
    url(r'^contest/(?P<contests_code>[-\w]+)/team/(?P<team_id>[0-9]+)/leave/$',
        views.LeaveTeam.as_view(), name='leave_team'),
    url(r'^contest/(?P<contests_code>[-\w]+)/public_leaderboard/$',
        views.PublicLeaderboard.as_view(), name='public_leaderboard'),
    url(r'^contest/(?P<contests_code>[-\w]+)/final_leaderboard/$',
        views.TestLeaderboard.as_view(), name='test_leaderboard'),
    url(r'^contest/(?P<contests_code>[-\w]+)/observe/$',
        views.StartObserving.as_view(), name='observe'),
    url(r'^contest/(?P<contests_code>[-\w]+)/unobserve/$',
        views.StopObserving.as_view(), name='unobserve'),
    url(r'^contest/(?P<contests_code>[-\w]+)/'
        r'submission/(?P<submission_id>[0-9]+)/select/$',
        views.SelectSubmission.as_view(), name='select_submission'),
    url(r'^contest/(?P<contests_code>[-\w]+)/'
        r'submission/(?P<submission_id>[0-9]+)/unselect/$',
        views.UnselectSubmission.as_view(), name='unselect_submission'),
    url(r'^contests/admin_hints/$', views.ContestAdminHints.as_view(),
        name='admin_hints'),
]

evolution/urls.py
from django.conf.urls import include, url

import system.urls

urlpatterns = [
    url(r'^', include(system.urls)),
]

system/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

import contests.urls

urlpatterns = [
    url(r'^$', views.NewsList.as_view(), name="news"),
    url(r'^user-settings/$', views.user_settings, name='user_settings'),
    url(r'^', include(contests.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>[a-zA-Z0-9_.-]+)$',
        views.AdminDownload.as_view(), name='media_path'),
    url(r'^invite/$', views.InviteView.as_view(), name="invite"),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^superuser_manual/$', views.SuperuserManual.as_view(),
        name='superuser_manual'),
    # below are the patterns made for front-end testing, they should not
    # be linked anywhere or change any data
    url(r'^test_view/messages$', views.messages_test_view),
    url(r'^test_view/static_messages$', views.static_messages_test_view),
]

contests/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.views.generic.base import ContextMixin, TemplateView, \
    View
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, CreateView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.exceptions import PermissionDenied, SuspiciousOperation
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db import transaction
from django.contrib import messages
from django.utils.safestring import mark_safe
from django_downloadview import BaseDownloadView
from django.conf import settings

from allauth.utils import build_absolute_uri

# contest stuff
from .models import Contest, ContestFactory, ContestStage, rejudge_contest, \
    build_leaderboard, StageIsClosed, ContestContext

# team stuff
from .models import Team, TeamMember, TeamInvitation, leave_team, \
    can_join_team_in_contest, in_team, teams_with_member_list, \
    accept_invitation, CannotJoin

# submission stuff
from .models import ContestSubmission, SubmissionData, submit, \
    rejudge_submission, SelectionError, select_submission, \
    unselect_submission, remaining_selections, ContestSubmissionEvent

from .forms import ContestForm, ContestCreateForm, SubmitForm

from grading.models import GradingAttempt
from system.models import ClientInfo
from system.views import PostDataView, add_static_message
from system.utils import calculate_once


def add_contest_messages(context, contest_context):
    cc = contest_context
    if cc.user_team is None and not cc.is_contest_admin:
        add_static_message(context, messages.INFO,
            "To participate in the contest, join a team"
            " or create your own.")


def contest_title(contest, text=None):
    return ' - '.join(filter(None, [contest.name, text]))


class ContestMixin(object):
    """
    Common logic for views within a Contest

    Uses:
        contest_related - iterable of fields that will be
            select_related for contest
    """

    base_contest_related = [
        'test_stage',
        'verification_stage',
        'test_stage__contest',
        'verification_stage__contest'
    ]
    contest_related = []

    title = None

    @property
    def contest_code(self):
        return self.kwargs['contests_code']

    @calculate_once
    def contest_context(self):
        return ContestContext(self.request.user, self.contest)

    @calculate_once
    def contest(self):
        contest_qs = Contest.objects.filter(code=self.contest_code)
        for related in self.base_contest_related + self.contest_related:
            contest_qs = contest_qs.select_related(related)
        return contest_qs.get()

    @property
    def contest_url(self):
        return reverse('contests:description', args=(self.contest.code,))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contest'] = self.contest
        context['contest_context'] = self.contest_context
        context['title'] = contest_title(self.contest, self.title)
        add_contest_messages(context, self.contest_context)
        return context


@login_required
def list(request):
    my_memberships = TeamMember.objects.filter(user=request.user). \
        select_related('contest').select_related('team')

    observed_contests = request.user.observed_contests.all()

    all_contests = Contest.objects.all()
    paginator = Paginator(all_contests, 10)

    page = request.GET.get('page')
    try:
        contests = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        contests = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        contests = paginator.page(paginator.num_pages)

    return render(request, 'contests/list.html', {
        'contests': contests,
        'my_memberships': my_memberships,
        'observed_contests': observed_contests
    })


class ContestCreate(LoginRequiredMixin, FormView):
    form_class = ContestCreateForm
    template_name = "contests/contest_create_form.html"

    contest = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'New Contest'
        return context

    def form_valid(self, form):
        factory = ContestFactory.from_dict(form.cleaned_data)
        self.code = form.cleaned_data['code']
        contest = factory.create()
        contest.observing.add(self.request.user)
        self.contest = contest
        return super().form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS,
            mark_safe('You have created contest <em>%s</em>. '
                'Now you can start setting it up.'
                % self.contest.name))
        return reverse('contests:setup', args=[self.code])


class ContestUpdate(UserPassesTestMixin, ContestMixin, FormView):
    form_class = ContestForm
    template_name = "contests/contest_form.html"
    title = "Settings"

    def test_func(self):
        return self.contest_context.is_contest_admin

    def get_code(self):
        return self.kwargs['contests_code']

    def get_initial(self):
        initial = super().get_initial()
        contest = Contest.objects. \
            select_related('description'). \
            select_related('rules'). \
            select_related('verification_stage'). \
            select_related('test_stage'). \
            get(code=self.get_code())
        initial['name'] = contest.name
        initial['code'] = contest.code
        initial['description'] = contest.description.source
        initial['rules'] = contest.rules.source
        initial['scoring_script'] = contest.scoring_script.source
        initial['bigger_better'] = contest.bigger_better
        initial['answer_for_verification'] = contest.verification_stage. \
            grader.answer
        initial['answer_for_test'] = contest.test_stage. \
            grader.answer
        initial['verification_begin'] = contest.verification_stage.begin
        initial['verification_end'] = contest.verification_stage.end
        initial['test_begin'] = contest.test_stage.begin
        initial['test_end'] = contest.test_stage.end
        initial['published_final_results'] = \
            contest.test_stage.published_results
        initial['selected_limit'] = contest.test_stage.selected_limit
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        contest = Contest.objects.get(code=self.get_code())
        context['contest'] = contest
        return context

    def form_valid(self, form):
        factory = ContestFactory.from_dict(form.cleaned_data)
        if form.cleaned_data['scoring_script']:
            factory.scoring_script = self.request.FILES.get('scoring_script')
        else:
            factory.scoring_script = False
        if form.cleaned_data['answer_for_verification']:
            factory.answer_for_verification = \
                self.request.FILES.get('answer_for_verification')
        else:
            factory.answer_for_verification = False
        if form.cleaned_data['answer_for_test']:
            factory.answer_for_test = \
                self.request.FILES.get('answer_for_test')
        else:
            factory.answer_for_test = False
        factory.update(self.contest)
        self.contest.observing.add(self.request.user)
        self.contest.save()
        return super().form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS,
            'Successfully updated contest settings.')
        return reverse('contests:setup', args=[self.contest.code])


class Description(LoginRequiredMixin, ContestMixin, TemplateView):
    template_name = "contests/title_and_text.html"
    title = "Description"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['content_title'] = 'Description'
        context['text'] = self.contest.description.html
        return context


class Rules(LoginRequiredMixin, ContestMixin, TemplateView):
    template_name = "contests/title_and_text.html"
    title = "Rules"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['content_title'] = 'Rules'
        context['text'] = self.contest.rules.html
        return context


class Submit(UserPassesTestMixin, ContestMixin, FormView):
    form_class = SubmitForm
    template_name = "contests/submit_form.html"
    title = "Submit"

    code = None

    def test_func(self):
        return self.contest_context.can_submit

    def get_success_url(self):
        return reverse('contests:my_submissions',
            args=[self.contest.code])

    def get_stage(self, form):
        stage_id = form.cleaned_data['stage']
        stage = ContestStage.objects.get(id=stage_id)
        if stage.contest != self.contest:
            raise PermissionDenied()
        return stage

    # TODO extract as available_stages, leave here pairing with stage.id
    @calculate_once
    def stage_choices(self):
        choices = []
        for stage in self.contest_context.stages:
            if self.contest_context.can_submit_in_stage(stage):
                choices.append(
                    (stage.id, self.contest_context.stage_names[stage.id])
                )
        return choices

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        choices = self.stage_choices
        kwargs['stages_available'] = choices
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not self.stage_choices:

contests/templates/contests/contest_create_form.html
{% extends "system/layout.html" %}

{% block content_title %} New Contest {% endblock %}

{% block content %}

<form id="create-contest-form" class="standard-form" action="{{ request.get_full_path }}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <ul>
        {{ form.as_ul }}
        <li> <input type="submit" value="Create" /> </li>
    </ul>
</form>

{% endblock content %}

contests/templates/contests/join_team.html
{% extends "contests/layout.html" %}

{% load standard %}

{% block contest_title %} Join <em>{{team.name}}</em> {% endblock %}

{% block content %}
<p>Do you want to join the team <strong>{{team.name}}</strong>?</p>

{% action_form 'join_team' 'join' request.url %}
{% endblock content %}

contests/templates/contests/leaderboard.html
{% extends "contests/layout.html" %}

{% block contest_title %} Leaderboard {% endblock %}

{% block content %}

{% block leaderboard_description %}{% endblock %}

{% if leaderboard %}
    <table class="result-table">
        <tr>
            <th>#</th>
            <th>Team</th>
            <th>Score</th>
        </tr>
        {% for entry in leaderboard %}
        <tr>
            <td class="position-cell">
                {{entry.position}}
            </td>
            <td class="team-cell">
                {{entry.team.name}}
                <ul class="team-members">
                    {% for member in entry.team.member_list %}
                        <li>{{member.user.get_full_name}}</li>
                    {% empty %}
                        <li><em>No members</em></li>
                    {% endfor %}
                </ul>
            </td>
            <td class="score-cell">
                {% if entry.score %}
                {{entry.score}}
                {% endif %}
            </td>
        </tr>
        {% empty %}
        {% endfor %}
    </table>
{% else %}
    <p>
        There are currently no teams in this leaderboard.
    </p>
{% endif %}
{% endblock content %}

contests/templates/contests/list.html
{% extends "system/layout.html" %}

{% block content_title %} Contests {% endblock %}

{% block content %}

{% if my_memberships %}
<div class=my-contests>
    <h2>My contests</h2>
    <span class="helptext">These are the contests that you participate in (you are a member of a team in the contest).</span>
    <ul>
        {% for membership in my_memberships %}
            <li><a href="{% url 'contests:description' membership.contest.code %}">{{membership.contest.name}}</a> in team <em>{{membership.team.name}}</em></li>
        {% endfor %}
    </ul>
</div>
{% endif %}

{% if observed_contests %}
<div class=observed-contests>
    <h2>Observed contests</h2>
    {% include "contests/observing-helptext.html" %}
    <ul>
        {% for contest in observed_contests %}
            <li><a href="{% url 'contests:description' contest.code %}">{{contest.name}}</a></li>
        {% endfor %}
    </ul>
</div>
{% endif %}

<div class="all-contests-list">
    <h2>All contests</h2>
    <ul>
    {% for contest in contests %}
        <li>
            <a href={% url 'contests:description' contest.code %}> {{contest.name}} ({{ contest.code }}) </a>
        </li>
    {% endfor %}
    </ul>

    <div class="pagination">
        <span class="step-links">
            {% if contests.has_previous %}
                <a href="?page={{ contests.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ contests.number }} of {{ contests.paginator.num_pages }}.
            </span>

            {% if contests.has_next %}
                <a href="?page={{ contests.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock content %}

contests/templates/contests/my_submissions.html
{% extends "contests/layout.html" %}

{% load standard %}
{% load contest %}

{% block contest_title %} My Submissions {% endblock %}

{% block content %}

{% if contest_context.is_contest_admin %}
<div class="helptext">
    You are the administrator of this contest, so this page shows all the technical submissions i.e. those sent by an administrator.
    See <a href="{% url 'contests:submissions' contest.code %}">Submissions</a>
    if you are interested in what was sent by contestants.
</div>
{% endif %}

<div class="submission-table">
    <table class="submission-table">
    <tr>
        <th>Id</th>
        <th>Stage</th>
        <th>Submission Time</th>
        <th>Comment</th>
        <th>Selected</th>
        <th>Result</th>
    </tr>
    {% for submission in submissions %}
        <tr class="submission_row" onclick="document.location = '{% url 'contests:submission' contest.code submission.id %}';">
            <td class="id-cell">{{submission.id}}</td>
            <td class="stage-cell">{% stage_name submission.stage contest_context %}</td>
            <td class="time-cell">{{submission.submission.created_at}}</td>
            <td class="comment-cell">{{submission.comment}}</td>
            <td class="selected-cell">
                {% submission_selection_state_icon submission %}
            </td>
            {% submission_result submission contest_context html_tag='td' additional_css_classes='result-cell' %}
        </tr>
    {% endfor %}
    </table>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ submissions.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock content %}

contests/templates/contests/public_leaderboard.html
{% extends "contests/leaderboard.html" %}

{% block contest_title %} Public Leaderboard {% endblock %}

{% block leaderboard_description %}
<p>This leaderboard shows the results of the verification stage. Your score here doesn't count to the final ranking. The only purpose of this leaderboard is to provide feedback about the quality of your solutions.</p>
{% endblock %}

contests/templates/contests/rejudge_all.html
{% extends "contests/layout.html" %}

{% load standard %}

{% block contest_title %} Rejudge All Submissions {% endblock %}

{% block content %}

<p>
	Here you can rejudge all submission in this contest. <strong>It can take a long time</strong>, depending on the number of submissions and how fast or slow is the scoring script.
</p>
<p>
	You can also rejudge individual submissions from their details view.
</p>

{% url 'contests:rejudge' contest.code as rejudge_url %}
{% action_form 'rejudge-all' 'Do it!' rejudge_url %}

{% endblock %}

contests/templates/contests/rejudge_done.html
{% extends "contests/layout.html" %}

{% block contest_title %} Rejudge Ordered {% endblock %}

{% block content %}
<p>
{% if contest_submission %}
	Submission <a href={% url 'contests:submission' contest.code contest_submission.id %}>{{contest_submission.id}}</a> was
{% else %}
	All submissions in the contest were
{% endif %}
	succesfully marked for rejudging.
{% endblock content %}

contests/templates/contests/submission.html
{% extends "contests/layout.html" %}

{% load standard %}
{% load contest %}

{% block contest_title %} Submission {{ contest_submission.id }} (<em>{{stage_name}}</em>) {% endblock %}

{% block content %}
{% if contest_context.is_contest_admin %}
    {% action_form 'rejudge-single' 'rejudge' rejudge_url %}
{% endif %}

<div class="main-result">
    {% submission_result contest_submission contest_context with_helptext=True %}
</div>

{% if contest_submission.stage.requires_selection %}
<div class="selection-box">
    <div class="selection-state">
        {% if contest_submission.selected %}
            <i class="material-icons selected-icon">grade</i> Selected <i class="material-icons selected-icon">grade</i>
        {% else %}
            <i class="material-icons not-selected-icon">clear</i>
            Not Selected
            <i class="material-icons not-selected-icon">clear</i>
        {% endif %}
    </div>
    {% if selection_change_active %}
        <div class="selection-change">
            {% if contest_submission.selected %}
                {% url 'contests:unselect_submission' contest.code contest_submission.id as unselect_url %}
                {% action_form 'unselect-action' 'unselect' unselect_url %}
            {% else %}
                {% url 'contests:select_submission' contest.code contest_submission.id as select_url %}
                {% action_form 'select-action' 'select this submission' select_url %}
            {% endif %}
            <div class="selection-remaining">
                remaining selections:
                    {% if remaining_selections != None %}
                        {{remaining_selections}}
                    {% else %}
                        ∞ {# infinity symbol #}
                    {% endif %}
            </div>
        </div>
    {% endif %}
    <div class="helptext">Only selected submissions will count in the leaderboard for this stage.</div>
</div>
{% endif %}

<ul class="submission-details">
    <li>Submitted at: <strong>{{submission.created_at}}</strong></li>
    <li><a href="{% url 'contests:submission_answer' contest.code submission.id %}">Answer</a></li>
    <li><a href="{% url 'contests:submission_source' contest.code submission.id %}">Source Code</a></li>
</ul>

{% if result == 'rejected' or result == 'accepted' and submission.scoring_msg %}
    <div class="submission-scoring-msg">
        <h2>
            {% if result == 'rejected' %}
                Rejection Reason
            {% else %}
                Scoring Comment
            {% endif %}
        </h2>
        <pre>{{submission.scoring_msg}}</pre>
    </div>
{% endif %}

{% if contest_context.is_contest_admin %}
    <hr>
    <h2>Submission Information:</h2>
    <ul class="submission-details">
        <li>Score: {{submission.score}}</li>
        <li>Status: {{submission.scoring_status}}</li>
        <li>Marked for grading: {{submission.needs_grading}}</li>
        <li>Grading requested at: {{submission.needs_grading_at}}</li>
        <li>Current attempt id: {{submission.current_attempt.id}}</li>
    </ul>

    <div class="submission-scoring-msg">
        <h2>Scoring Message</h2>
        <pre>{{submission.scoring_msg}}</pre>
    </div>

    <h2>Grading history</h2>
    {% for attempt in grading_history %}
        <div class="submission-grading-attempt">
            <h3>Attempt Id: <strong>{{attempt.id}}</strong></h3>
            <ul class="submission-details">
                <li>Started at: {{attempt.created_at}}</li>
                <li>Finished at: {{attempt.finished_at}}</li>
                <li>Finished: {{attempt.finished}}</li>
                <li>succeeded: {{attempt.succeeded}}</li>
                <li>Score: {{attempt.score}}</li>
                <li>Aborted: {{attempt.aborted}}</li>
                <li>Log: {% if attempt.log %}<a href={{attempt.log.url}}>{{attempt.log}} {% else %} nonexistent {% endif %}</a></li>
            </ul>
                <div class="submission-scoring-msg">
                    <h4>Scoring Message</h4>
                    <pre>{{submission.scoring_msg}}</pre>
                </div>
        </div>
    {% endfor %}
{% endif %}
{% endblock content %}

contests/templates/contests/submission_result.html
<{{html_tag}} class="{{classes}}">
    {{text}}
    {% if helptext %}
        <div class="helptext">{{helptext}}</div>
    {% endif %}
</{{html_tag}}>

contests/templates/contests/submissions.html
{% extends "contests/layout.html" %}

{% load standard %}

{% block contest_title %} Submissions {% endblock %}

{% block content %}
<div class="submission-table">
    <table class="submission-table">
    <tr>
        <th>Team</th>
        <th>Id</th>
        <th>Submission Time</th>
        <th>Score</th>
        <th>Comment</th>
    </tr>
    {% for submission in submissions %}
        <tr class="submission_row" onclick="document.location = '{% url 'contests:submission' contest.code submission.id %}';">
            <td class="team-cell">{{submission.team}}</td>
            <td class="id-cell">{{submission.id}}</td>
            <td class="time-cell">{{submission.submission.created_at}}</td>
            <td class="score-cell">{{submission.submission.score}}</td>
            <td class="comment-cell">{{submission.comment}}</td>
        </tr>
    {% endfor %}
    </table>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ submissions.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock content %}

contests/templates/contests/submit_form.html
{% extends "contests/layout.html" %}

{% block contest_title %} Send Submission {% endblock %}

{% block content %}

{% if contest_context.is_contest_admin %}

<p>
You are the administator of this contest. Your submission will be considered <strong>technical</strong> and won't count in the leaderboard.
</p>
{% endif %}

<form id="submit-form" class="standard-form" action="{% url 'contests:submit' contest.code %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <ul>
        {{ form.as_ul }}
        <li> <input type="submit" value="Submit" /> </li>
    </ul>
</form>

{% endblock content %}

contests/templates/contests/teams.html
{% extends "contests/layout.html" %}

{% block contest_title %} Teams {% endblock %}

{% block content %}
{% if contest_context.can_create_team %}
    <a class="action-button" href={% url 'contests:new_team' contest.code %}>new team</a>
{% endif %}
<div class="teams-list">
    {% if teams %}
    <p>The teams in alphabetic order:</p>
    <ol>
    {% for team in teams %}
        <li>
            <a href="{% url 'contests:team' contest.code team.id %}">{{team.name}} </a>
            <ul class="teams-member-list">
                {% for member in team.member_list %}
                    <li>
                        {{member.user.get_full_name}}
                    </li>
                {% empty %}
                    <li><em>No members</em></li>
                {% endfor %}
            </ul>
        </li>
    {% empty %}
    <p>
    {% endfor %}
    </ol>
    {% else %}
    <p> There are currently no teams registered for this contest.</p>
    {% endif %}
</div>
{% endblock content %}

contests/templates/contests/title_and_text.html
{% extends "contests/layout.html" %}

{% block content %}
    <div class="text">
        {{text | safe}}
    </div>
{% endblock content %}