contests/urls.py
from django.conf.urls import url

from . import views

app_name = 'contests'
urlpatterns = [
    url(r'^contests/$', views.list, name='list'),
    url(r'^contests/setup/$', views.ContestCreate.as_view(), name='setup_new'),
    url(r'^contest/(?P<contests_code>[-\w]+)/$', views.Description.as_view(),
        name='description'),
    url(r'^contest/(?P<contests_code>[-\w]+)/rules$', views.Rules.as_view(),
        name='rules'),
    url(r'^contest/(?P<contests_code>[-\w]+)/submit/$',
        views.Submit.as_view(), name='submit'),
    url(r'^contest/(?P<contests_code>[-\w]+)/submissions/$',
        views.Submissions.as_view(), name='submissions'),
    url(r'^contest/(?P<contests_code>[-\w]+)/my_submissions/$',
        views.MySubmissions.as_view(), name='my_submissions'),
    url(r'^contest/(?P<contests_code>[-\w]+)/'
        r'submission/(?P<submission_id>[0-9]+)/$',
        views.SubmissionView.as_view(), name='submission'),
    url(r'^contest/(?P<contests_code>[-\w]+)/'
        r'submission/(?P<submission_id>[0-9]+)/answer/$',
        views.DownloadSubmissionAnswer.as_view(), name='submission_answer'),
    url(r'^contest/(?P<contests_code>[-\w]+)/'
        r'submission/(?P<submission_id>[0-9]+)/source/$',
        views.DownloadSubmissionSource.as_view(), name='submission_source'),
    url(r'^contest/(?P<contests_code>[-\w]+)/'
        r'rejudge/(?P<submission_id>[0-9]+)/$',
        views.SubmissionRejudgeView.as_view(), name='rejudge'),
    url(r'^contest/(?P<contests_code>[-\w]+)/rejudge/$',
        views.ContestRejudgeView.as_view(), name='rejudge'),
    url(r'^contest/(?P<contests_code>[-\w]+)/setup/$',
        views.ContestUpdate.as_view(), name='setup'),
    url(r'^contest/(?P<contests_code>[-\w]+)/teams/$',
        views.Teams.as_view(), name='teams'),
    url(r'^contest/(?P<contests_code>[-\w]+)/teams/new$',
        views.TeamCreate.as_view(), name='new_team'),
    url(r'^contest/(?P<contests_code>[-\w]+)/team/(?P<team_id>[0-9]+)/$',
        views.TeamView.as_view(), name='team'),
    url(r'^contest/(?P<contests_code>[-\w]+)/team/(?P<team_id>[0-9]+)/join/$',
        views.JoinTeam.as_view(), name='join_team'),
    url(r'^contest/(?P<contests_code>[-\w]+)/'
        r'team/(?P<team_id>[0-9]+)/invite/$',
        views.TeamInvitationView.as_view(), name='invite_to_team'),
    url(r'^contest/(?P<contests_code>[-\w]+)/team/(?P<team_id>[0-9]+)/leave/$',
        views.LeaveTeam.as_view(), name='leave_team'),
    url(r'^contest/(?P<contests_code>[-\w]+)/public_leaderboard/$',
        views.PublicLeaderboard.as_view(), name='public_leaderboard'),
    url(r'^contest/(?P<contests_code>[-\w]+)/final_leaderboard/$',
        views.TestLeaderboard.as_view(), name='test_leaderboard'),
    url(r'^contest/(?P<contests_code>[-\w]+)/observe/$',
        views.StartObserving.as_view(), name='observe'),
    url(r'^contest/(?P<contests_code>[-\w]+)/unobserve/$',
        views.StopObserving.as_view(), name='unobserve'),
    url(r'^contest/(?P<contests_code>[-\w]+)/'
        r'submission/(?P<submission_id>[0-9]+)/select/$',
        views.SelectSubmission.as_view(), name='select_submission'),
    url(r'^contest/(?P<contests_code>[-\w]+)/'
        r'submission/(?P<submission_id>[0-9]+)/unselect/$',
        views.UnselectSubmission.as_view(), name='unselect_submission'),
    url(r'^contests/admin_hints/$', views.ContestAdminHints.as_view(),
        name='admin_hints'),
]

evolution/urls.py
from django.conf.urls import include, url

import system.urls

urlpatterns = [
    url(r'^', include(system.urls)),
]

system/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

import contests.urls

urlpatterns = [
    url(r'^$', views.NewsList.as_view(), name="news"),
    url(r'^user-settings/$', views.user_settings, name='user_settings'),
    url(r'^', include(contests.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>[a-zA-Z0-9_.-]+)$',
        views.AdminDownload.as_view(), name='media_path'),
    url(r'^invite/$', views.InviteView.as_view(), name="invite"),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^superuser_manual/$', views.SuperuserManual.as_view(),
        name='superuser_manual'),
    # below are the patterns made for front-end testing, they should not
    # be linked anywhere or change any data
    url(r'^test_view/messages$', views.messages_test_view),
    url(r'^test_view/static_messages$', views.static_messages_test_view),
]

system/models.py
import reprlib
import html
from datetime import timedelta

from django.db import models, transaction
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings
from django.core.mail import EmailMessage
from django.contrib.sites.models import Site
from django.core.exceptions import ValidationError
from allauth.account.models import EmailAddress
from allauth.utils import build_absolute_uri

from .markdown import markdown_to_html

SOURCE_LANGUAGES = (
    ('html', 'HTML'),
    ('plaintext', 'Plain Text'),
    ('markdown', 'Github-flavored Markdown')
)


class Post(models.Model):
    source_lang = models.CharField(max_length=20, default='markdown',
        choices=SOURCE_LANGUAGES)
    source = models.TextField()
    html = models.TextField()

    def to_data(self):
        return PostData(
            source_lang=self.source_lang,
            source=self.source,
            html=self.html
        )

    def from_data(self, data):
        self.source_lang = data.source_lang
        self.source = data.source
        self.html = data.html

    @classmethod
    def new_from_data(cls, data):
        post = cls()
        post.from_data(data)
        post.save()
        return post

    def __str__(self):
        return str(self.id) + ' (' + self.source_lang + ') ' + \
            reprlib.repr(self.source)


post_source_processors = {
    'html': lambda source: source,  # identity
    'plaintext': html.escape,
    'markdown': markdown_to_html
}


class PostData(object):
    source_lang = None
    source = None
    html = None

    def __init__(self, source=None, source_lang=None, html=None):
        self.source = source
        self.source_lang = source_lang
        self.html = html

    @classmethod
    def from_source(cls, source, source_lang):
        data = cls()
        data.source = source
        data.source_lang = source_lang
        return data

    def build_html(self):
        self.html = post_source_processors[self.source_lang](self.source)


class NewsItem(models.Model):
    created = models.DateTimeField()
    title = models.CharField(max_length=200)
    content = models.OneToOneField('Post')

    def __str__(self):
        return str(self.id) + ': ' + reprlib.repr(self.title)


def validate_email_not_used(email):
    existing_email = EmailAddress.objects.filter(email=email). \
        first()
    if existing_email:
        existing_user = existing_email.user
        raise ValidationError(
            "Email already associated with user: %s (%s)." %
            (existing_user.get_full_name(), existing_user.username))


class Invitation(models.Model):
    invited_email = models.EmailField(validators=[validate_email_not_used],
        verbose_name="User email")
    invited_by = models.ForeignKey('auth.User', null=True)
    secret_code = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False)

    def is_expired(self):
        latest_acceptable = self.created_at + \
            timedelta(days=settings.INVITATION_EXPIRY)
        return timezone.now() > latest_acceptable

    def prepare(self):
        self.secret_code = User.objects.make_random_password(length=16)

    def send_email(self):
        site = Site.objects.get_current()
        subject = '[%s] Invitation' % site.name
        to = self.invited_email
        full_signup_url = build_absolute_uri(None, settings.SIGNUP_URL)
        # TODO, move to a template or something
        body_template = """\
Hello,

You have been invited to use {site_name}. We hope you'll like it.

Invited email: {invited_email}
Secret code: {secret_code}
Signup url: {full_signup_url}

Enjoy,
{site_name} Team
"""
        body = body_template.format(
            site_name=site.name,
            invited_email=self.invited_email,
            secret_code=self.secret_code,
            full_signup_url=full_signup_url
        )
        email = EmailMessage(subject, body, to=[to])
        email.send()


class ClientInfo(models.Model):
    client_address = models.CharField(max_length=255)
    user_agent = models.TextField()
    referer = models.TextField()

    def extract_from(self, request):
        self.client_address = request.META.get('HTTP_X_FORWARDED_FOR',
            request.META.get('REMOTE_ADDR', 'unknown'))
        self.user_agent = request.META.get('HTTP_USER_AGENT', 'unknown')
        self.referer = request.META.get('HTTP_REFERER', 'unknown')

    def __str__(self):
        return ' '.join([self.client_address, self.user_agent, self.referer])


class SystemSettings(models.Model):
    class Meta:
        verbose_name = "System settings"
        verbose_name_plural = "System settings"

    # hack to ensure there is only one settings row
    # TODO ensure no one changes this value
    force_singleton = models.CharField(max_length=1, default='x', unique=True)

    global_message = models.ForeignKey('Post', related_name='+', null=True)
    footer = models.ForeignKey('Post', related_name='+', null=True)

    @classmethod
    @transaction.atomic
    def get(cls):
        return cls.objects.get_or_create()[0]


def validate_x(whatever):
    """
    django migrations won't let me delete it
    """
    pass

system/forms.py
from django import forms

from .models import Post, Invitation


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['source_lang', 'source']

    def save(self, commit=True):
        post = super().save(commit=False)
        post_data = post.to_data()
        post_data.build_html()
        post.from_data(post_data)
        print('post_html:', post.html)
        if commit:
            post.save()
        return post


class InviteForm(forms.ModelForm):

    class Meta:
        model = Invitation
        fields = ['invited_email']


class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    secret_code = forms.CharField(max_length=30, label="Secret Code")

    def signup(self, request, user):
        secret = self.cleaned_data.get('secret_code')
        invitation = Invitation.objects.filter(secret_code=secret).first()
        invitation.accepted = True
        invitation.save()
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()

    def clean(self):
        cleaned_data = super().clean()
        secret = cleaned_data.get('secret_code')
        if not secret:
            # the field is already required
            return cleaned_data
        secret = secret.strip()
        cleaned_data['secret_code'] = secret  # stripped
        invitation = Invitation.objects.filter(secret_code=secret).first()
        if not invitation:
            self.add_error('secret_code', 'Wrong Secret Code')
        if invitation.accepted:
            self.add_error('secret_code', 'Secret Code already used')
        if invitation.is_expired():
            self.add_error('secret_code',
                'Invitation expired, maybe request a new one.')
        return cleaned_data

system/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, FormView
from django.views.generic.base import ContextMixin
from django.views.generic.list import ListView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ImproperlyConfigured
from django_downloadview import StorageDownloadView
from django.template.loader import render_to_string
from django.core.urlresolvers import reverse
from django.utils.safestring import mark_safe
from django.contrib import messages
from django.contrib.messages.storage.base import Message

from .forms import InviteForm

from .models import NewsItem, PostData


# Sometimes it is useful to show some messages only for
# the original request. Permanent messages are example of that.
# Especially, when they are specific to some part of the system
def add_static_message(context, level, msg, extra_tags=""):
    msg = Message(level, msg, extra_tags)
    if 'static_messages' in context:
        context['static_messages'].append(msg)
    else:
        context['static_messages'] = [msg]


class AdminDownload(UserPassesTestMixin, StorageDownloadView):

    def test_func(self):
        return self.request.user.is_superuser


def title(text=None):
    return ' - '.join(filter(None, ["Evolution", text]))


class NewsList(ListView):
    context_object_name = 'news'
    template_name = "system/news.html"
    paginate_by = 10
    queryset = NewsItem.objects.select_related('content').all()


@login_required
def user_settings(request):
    return render(request, 'system/user_settings.html', {})


class PostDataView(ContextMixin, View):
    """
    Generic View that allows "static posts".

    It renders the template in the specified language then builds html using
    the same mechanism as Posts. Result is added to the context as `text`.
    Then it renders external template, with the resulting context.

    Currently it goes through building html on every request, if this becomes
    a performance issue, we may want to cache that.
    """

    post_template_name = None
    source_lang = None
    external_template_name = "system/title_and_text.html"

    def get(self, request, *args, **kwargs):
        if not self.post_template_name:
            raise ImproperlyConfigured(
                "You need to specify post_template_name")
        if not self.source_lang:
            raise ImproperlyConfigured("You need to specify source_lang")

        context = self.get_context_data(**kwargs)
        source = render_to_string(self.post_template_name, context=context,
            request=request)
        post = PostData.from_source(source, self.source_lang)
        post.build_html()
        context['text'] = post.html
        return render(request, self.external_template_name, context)


class InviteView(UserPassesTestMixin, FormView):
    form_class = InviteForm
    template_name = "system/invite.html"

    def test_func(self):
        return self.request.user.is_superuser

    def form_valid(self, form):
        form.instance.invited_by = self.request.user
        form.instance.prepare()
        invitation = form.save()
        invitation.send_email()
        messages.add_message(self.request, messages.SUCCESS,
            mark_safe("Invitation sent to <strong>%s</strong>" %
                invitation.invited_email))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('invite')


def messages_test_view(request):
    messages.set_level(request, messages.DEBUG)
    messages.add_message(request, messages.SUCCESS,
        mark_safe('Success. You are no longer observing contest '
            '<strong>Data Science Cup</strong>.'))
    messages.add_message(request, messages.SUCCESS,
        mark_safe('<p>Success</p><p>You have changed the contests. '
            'Lorem ipsum dolor sit'
            'amet augue at tortor. Praesent et magnis dis parturient montes,'
            'nascetur rig di amet.</p>'
            '<p>Lorem ipsum Fugiat culpa mollit Duis enim dolor proident et'
            'elit adipisicing velit est pariatur dolor cupidatat Duis'
            'incididunt consequat Ut ullamco commodo aliquip esse officia'
            ' cupidatat in aute irure dolor consequat minim.</p>'))
    messages.add_message(request, messages.DEBUG,
        mark_safe('This is a debug message. <pre>blebleble</pre>'))
    messages.add_message(request, messages.INFO,
        mark_safe('This is an info message. The weather is nice today.'))
    messages.add_message(request, messages.WARNING,
        mark_safe("Warning: It's a trap!"))
    messages.add_message(request, messages.ERROR,
        mark_safe("Error. Something blew up badly."))
    return render(request, 'system/title_and_text.html', {
        'title': title('Message Test'),
        'content_title': 'Message Test',
        'text': "Nothing to do here"
    })


def static_messages_test_view(request):
    context = {
        'title': title('Static Message Test View')
    }
    if request.method == 'GET':
        add_static_message(context, messages.INFO, 'get1')
        add_static_message(context, messages.INFO, 'get2')
        return render(request, 'system/title_and_text.html', context)
    else:
        add_static_message(context, messages.INFO, 'other1')
        add_static_message(context, messages.INFO, 'other2')
        return redirect('/test_view/static_messages')


class SuperuserManual(UserPassesTestMixin, PostDataView):
    post_template_name = "contests/superuser_manual.md"
    source_lang = 'markdown'
    content_title = "Superuser Manual"

    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['content_title'] = self.content_title
        return context

system/templates/system/action-form.html
<form method="POST" id="{{id}}" action="{{url}}" class="{{css_class}}">
    {% csrf_token %}
    <input type="submit" value="{{text}}">
</form>

system/templates/system/announcements.html
{% extends "system/layout.html" %}

{% block content %}
  <h1>Announcements</h1>
  <div class="news-item">
    <h2> ble ble ble </h2>
    <p>
    Lorem ipsum Commodo fugiat amet voluptate velit sit minim non esse cillum voluptate id aliqua eiusmod id deserunt proident Duis ex.
    </p>
  </div>
  <div class="news-item">
    <h2> fdsfadafsfdsfas fdsfdsfssdfds </h2>
    <p>
    Lorem ipsum Deserunt cillum in ex elit Excepteur consectetur sint dolor amet consequat exercitation exercitation sunt voluptate sint dolore dolor esse sunt quis veniam aliqua in pariatur elit labore dolore consequat nulla ad in et veniam aute esse in culpa aliqua amet.
    </p>
  </div>
  <div class="news-item">
    <h2> sdsf  sdfjsldsfl sfsdlfdslsd dsfdse </h2>
    <p>
    Lorem ipsum Excepteur dolore sit tempor enim sit ad Excepteur consectetur eiusmod laborum tempor pariatur cillum irure aliqua dolor sed officia sed aliquip dolore ex culpa Duis ex elit adipisicing Duis sunt culpa deserunt commodo velit anim id adipisicing commodo cupidatat est dolor non tempor laborum id Ut enim in occaecat in enim in elit ex est ullamco in qui Duis non ullamco in sint anim ullamco cillum exercitation Excepteur minim consectetur anim fugiat Excepteur Excepteur ut culpa qui irure aliqua Excepteur aliqua exercitation et Ut in ex pariatur aute dolore Duis amet do adipisicing consectetur elit nostrud consectetur et incididunt ut sit ad anim eiusmod officia est commodo tempor qui irure consequat culpa aute velit et nulla veniam laborum eu qui non non deserunt incididunt Ut labore enim ad mollit aliquip voluptate consequat in do exercitation aliqua culpa sed veniam ex ut ad dolor dolor tempor do minim in aliquip ea dolor nostrud amet aliqua in eu eu deserunt sint mollit in adipisicing fugiat non culpa incididunt minim ullamco ex incididunt nulla cupidatat consectetur est exercitation ut pariatur dolore ullamco ullamco ullamco est deserunt ut magna aute Ut Excepteur eiusmod quis non laborum aliqua dolore amet ut anim nisi fugiat elit veniam anim qui in dolore nostrud elit nulla sint commodo in Excepteur mollit tempor sed nulla irure irure magna in officia minim et cillum qui nisi ea reprehenderit quis aute Excepteur enim Excepteur culpa ullamco ad veniam exercitation sunt nulla Duis incididunt mollit exercitation ad Ut sint.
    </p>
  </div>
  <div class="news-item">
    <h2> ble bledsfdssdfsd ble </h2>
    <p>
    Lorem ipsum Ad ex consequat ut mollit sunt proident nulla pariatur aliqua eu dolore enim aliquip aliquip aliquip commodo in sed ullamco non enim sit mollit sunt in sed nulla tempor non sunt ex esse ut aliquip laboris.
    </p>
  </div>
  <div class="news-item">
    <h2> ble bledsfdssdfsd ble </h2>
    <p>
    Lorem ipsum Irure enim nulla tempor aliquip tempor ex id ut Duis ullamco qui labore cillum fugiat aliqua ut dolore quis Ut cupidatat sed est officia incididunt elit magna ea.
    </p>
  </div>
  <div class="news-item">
    <h2> ble bledsfdssdfsd ble </h2>
    <p>
    Lorem ipsum Ea adipisicing officia amet amet aliqua dolor eiusmod dolor aute nulla exercitation in qui incididunt velit pariatur amet eiusmod exercitation velit sunt deserunt eiusmod dolor aliquip enim Ut dolore irure adipisicing commodo anim Ut aliquip laborum dolor fugiat nostrud ullamco id in exercitation non velit et eu Ut ex consectetur elit dolore et enim incididunt officia Duis commodo consectetur aliquip ea veniam amet aute est ea exercitation nostrud anim consectetur eiusmod fugiat dolor elit sit et eu qui ex ut non ex nisi in sunt aliqua Excepteur velit eu enim enim in ea eu occaecat ex et ullamco mollit est proident fugiat mollit minim aliquip pariatur commodo nulla tempor elit id ex Duis sint irure amet aliqua eu adipisicing esse laboris mollit non ullamco laboris laboris et amet dolore fugiat amet aliquip exercitation minim exercitation ea amet mollit Duis mollit reprehenderit.
    </p>
  </div>
</div>
{% endblock content %}

system/templates/system/invite.html
{% extends "system/layout.html" %}

{% block title %} Invite {% endblock %}

{% block content_title %} Invite {% endblock %}

{% block content %}

<form id="invite-user-form" class="standard-form" action="{{ request.get_full_path }}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <ul>
        {{ form.as_ul }}
        <li> <input type="submit" value="Invite" /> </li>
    </ul>
</form>

{% endblock content %}

system/templates/system/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %} {{ title }} {% endblock %} </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="/static/highlighting-github.css">
  </head>
  <body>
    <div class="container">
      {% if system_settings.global_message.html %}
        <div class="global-message">
          {{system_settings.global_message.html|safe}}
        </div>
      {% endif %}
      <div class="left-pane">
        <div class="logo">
          <a href={{logo_link}}><img src="/static/logo.png"></a>
        </div>
        <div class="page-status">
          {% block status %}{% endblock status %}
        </div>
        {% include "system/left-pane.html" %}
      </div>
      <div class="page-content">
        <h1>{% block content_title %} {{ content_title }} {% endblock %}</h1>
        {% if messages or static_messages %}
          <ul class="messages">
              {% for message in messages %}
                <li>
                  <div class="message-box {{ message.tags }}">
                    <div class="message-icon"><i class="material-icons message-icon"></i></div>
                    <div class="message">{{ message }} </div>
                  </div>
                </li>
              {% endfor %}
              {% for message in static_messages %}
                <li>
                  <div class="message-box {{ message.tags }}">
                    <div class="message-icon"><i class="material-icons message-icon"></i></div>
                    <div class="message">{{ message }} </div>
                  </div>
                </li>
              {% endfor %}
          </ul>
        {% endif %}
        {% block content %}{% endblock %}
      </div>
    </div>
    {% if system_settings.footer.html %}
      <div class="footer">
        {{system_settings.footer.html|safe}}
      </div>
    {% endif %}
  </body>
</html>

system/templates/system/left-pane.html
{% load standard %}

{% if contest %}
  <div class="contest-menu">
    <h2>contest menu</h2>
    <ul>
      <li class="menu-item">
        <a href="{% url 'contests:description' contest.code %}">Description</a>
      </li>
      <li class="menu-item">
        <a href="{% url 'contests:rules' contest.code %}">Rules</a>
      </li>
      {% if contest_context.can_submit %}
        <li class="menu-item"><a href="{% url 'contests:submit' contest.code %}">Send Submission</a></li>
      {% endif %}
      {% if contest_context.user_team or contest_context.is_contest_admin %}
        <li class="menu-item"><a href="{% url 'contests:my_submissions' contest.code %}">My Submissions</a></li>
      {% endif %}
      {% if contest_context.can_see_all_submissions %}
        <li class="menu-item"><a href="{% url 'contests:submissions' contest.code %}">Submissions</a></li>
      {% endif %}
      {% if contest_context.can_see_verification_leaderboard %}
        <li class="menu-item"><a href="{% url 'contests:public_leaderboard' contest.code %}">Public Leaderboard</a></li>
      {% endif %}
      {% if contest_context.can_see_test_leaderboard %}
        <li class="menu-item"><a href="{% url 'contests:test_leaderboard' contest.code %}">Final Leaderboard</a></li>
      {% endif %}
      {% if contest_context.user_team %}
        <li class="menu-item"><a href="{% url 'contests:team' contest.code contest_context.user_team.id %}">My Team</a></li>
      {% endif %}
        <li class="menu-item"><a href="{% url 'contests:teams' contest.code %}">Teams</a></li>
      {% if contest_context.is_contest_admin %}
        <li class="menu-item"><a href="{% url 'contests:setup' contest.code %}">Settings</a></li>
        <li class="menu-item"><a href="{% url 'contests:rejudge' contest.code %}">Rejudge</a></li>
      {% endif %}
    </ul>
  </div>
{% endif %}
<div class="system-menu">
  <h2>system menu</h2>
  <ul>
    <li class="menu-item"><a href="{% url 'news' %}">News</a></li>
    {% if request.user.is_authenticated %}
    <li class="menu-item"><a href="{% url 'contests:list' %}">Contests</a></li>
    {% endif %}
    {% if request.user.is_superuser %}
    <li class="menu-item"><a href="{% url 'contests:setup_new' %}">New Contest</a></li>
    <li class="menu-item"><a href="{% url 'admin:index' %}">Admin Panel</a></li>
    <li class="menu-item"><a href="{% url 'invite' %}">Invite</a></li>
    <li class="menu-item"><a href="{% url 'superuser_manual' %}">Superuser Manual</a></li>
    <li class="menu-item"><a href="{% url 'contests:admin_hints' %}">Hints for Contest Admins</a></li>
    {% endif %}
    {% if request.user.is_authenticated %}
    <li class="menu-item"><a href="{% url 'user_settings' %}">User Settings</a></li>
    {% endif %}
  </ul>
</div>

<div class="left-user">
  {% if user.is_authenticated %}
    <div class="current-user">
      User:
      <span class="current-user-username"> {{user.username}} </span>
    </div>
    {% url 'account_logout' as logout_url %}
    {% action_form 'logout-button' "log out" logout_url %}
  {% else %}
    <form method="post" action="{% url 'account_login' %}?next={% firstof request.GET.next redirect_next request.path %}">
      {% csrf_token %}
      <ul>
        <li>
          <input id="left_username" maxlength="254" name="login" type="text" placeholder="Username">
        </li>
        <li>
          <input id="left_password" name="password" type="password" placeholder="Password">
        </li>
        <li>
          <input type="submit" value="log in" />
        </li>
      </ul>
    </form>
  {% endif %}
</div>

system/templates/system/news.html
{% extends "system/layout.html" %}

{% block content_title %} News {% endblock %}

{% block content %}
  {% for news_item in news %}
  <div class="news-item">
    <h2> {{news_item.title}} </h2>
    <div class="news-body">
    {{news_item.content.html|safe}}
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

system/templates/system/title_and_text.html
{% extends "system/layout.html" %}

{% block content %}
    <div class="text">
        {{text | safe}}
    </div>
{% endblock content %}

system/templates/system/user_settings.html
{% extends "system/layout.html" %}

{% block content %}

<h1>User settings</h1>


<p><a href="{% url 'account_change_password' %}">Change password</a></p>
<p><a href="{% url 'account_email' %}">Manage email addresses</a></p>

{% endblock content %}